replicaCount: 1

image:
  repository: 192.168.100.102:5000/cups-reporting
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000
  cupsPort: 631

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
replicaCount: 1

image:
  repository: ""
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5000
  cupsPort: 631

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
