apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: cups
      port: 631
      targetPort: 631
      nodePort: 30631
    - name: reporting
      port: 5000
      targetPort: 5000
      nodePort: 30500
